MxOnline/urls.py
from django.contrib import admin
from django.urls import path
import xadmin
from apps.operations.views import IndexView
# from apps.users import views
from django.views.generic import TemplateView
from apps.users.views import LoginView, LogoutView
from apps.organizations.views import OrgView
from django.conf.urls import url,include
from django.views.static import serve
from MxOnline.settings import MEDIA_ROOT
urlpatterns = [
    path('admin/', admin.site.urls),
    path('xadmin/', xadmin.site.urls),
    # path('', TemplateView.as_view(template_name='index.html'),name='index'),
    path('courselist/', TemplateView.as_view(template_name='course-list.html'), name='course_list'),
    path('', IndexView.as_view(),name='index'),
    path('login/', LoginView.as_view(),name='login'),
    # 配置授课机构列表展示
    path('orglist/', OrgView.as_view(),name='org_list'),
    path('logout/',LogoutView.as_view(), name ='logout'),
#     配置上传文件的访问url
    url(r'^media/(?P<path>.*)$',serve,{"document_root":MEDIA_ROOT}),
    # 授课机构相关操作
    url(r'^org/', include(('apps.organizations.urls', 'organizations'), namespace='org')),
    # 课程相关页面
    url(r'^course/', include(('apps.courses.urls', 'courses'), namespace='course')),
    # 用户操作相关
    url(r'^op/', include(('apps.operations.urls', 'operations'), namespace='op')),
    url(r'^users/', include(('apps.users.urls', 'users'), namespace='users')),

]

apps/courses/urls.py
from django.conf.urls import url, include
from apps.organizations.views import OrgView,AddAsk
from apps.courses.views import CourseListView,CourseDetailView
from apps.courses.views import CourseListView, CourseDetailView, CouersLessonView, CouersCommentsView,VideoView
urlpatterns = [
    url(r'^list/',CourseListView.as_view(), name='list'),
    # url(r'^detail/',CourseDetailView.as_view(), name='detail'),
    url(r'^(?P<course_id>\d+)/$', CourseDetailView.as_view(), name='detail'),

    url(r'^(?P<course_id>\d+)/lesson/$', CouersLessonView.as_view(), name='lesson'),
    url(r'^(?P<course_id>\d+)/comments/$', CouersCommentsView.as_view(), name='comments'),
    url(r'^(?P<course_id>\d+)/video/(?P<video_id>\d+)$', VideoView.as_view(), name='video'),
]

apps/operations/urls.py
from django.conf.urls import url

from apps.operations.views import AddFavView,CommentView

urlpatterns = [
    url(r'^fav/$', AddFavView.as_view(), name='fav'),
    url(r'^comment/$', CommentView.as_view(), name='comment'),
]

apps/organizations/urls.py
from django.conf.urls import url, include

from apps.organizations.views import OrgView, AddAsk, TeacherListView, TeacherDeatailView

urlpatterns = [
    url(r'^list/', OrgView.as_view(), name='list'),
    url(r'^add_ask/$', AddAsk.as_view(), name='add_ask'),
 # 讲师相关
    url(r'^teachers/$', TeacherListView.as_view(), name='teachers'),
    url(r'^teachers/(?P<teacher_id>\d+)$', TeacherDeatailView.as_view(), name='teacher_detail'),

]

apps/users/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

from apps.users.views import *
from apps.users.views import UserInfoView, MyFavOrgView, MyFavCourseView, MyFavTeacherView, ChangePwdView

urlpatterns = [
    url(r'^info/$', UserInfoView.as_view(), name='info'),

    url(r'^mycourse/$',
        login_required(TemplateView.as_view(template_name='usercenter-mycourse.html'), login_url='/login/'),
        {"current_page": "mycourse"}, name='mycourse'),
    url(r'^message/$', login_required(TemplateView.as_view(template_name='usercenter-message.html'), login_url = '/login/'), {"current_page": "message" }, name='message'),
    url(r'^myfavorg/$', MyFavOrgView.as_view(), name='myfavorg'),
    url(r'^myfav_teacher/$', MyFavTeacherView.as_view(), name='myfav_teacher'),
    url(r'^myfav_course/$', MyFavCourseView.as_view(), name='myfav_course'),
    url(r'^update/pwd/$', ChangePwdView.as_view(), name='update_pwd'),

]

xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getfullargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.urls.base import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass


def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)


def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getfullargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):

    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user,
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user

        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

templates/base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    {#    <title>课程机构列表 - 慕学在线网</title>#}
    <title>{% block title %}首页-慕学在线{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="/static/css/animate.css">
    <link rel="stylesheet" type="text/css" href="/static/css/style.css">

    {% block custom_css %}

    {% endblock %}

    <script src="/static/js/jquery.min.js" type="text/javascript"></script>
    <script src="/static/js/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>

</head>
<body>
<section class="headerwrap ">
    <header>
        <div class=" header">
            <div class="top">
                <div class="wp">
                    <div class="fl"><p>服务电话：<b>400-888-888</b></p></div>

                    {% if user.is_authenticated %}
                        <div class="personal">
                            <dl class="user fr">
                                    <dd>{% if user.nick_name %}{{ user.nick_name }}{% else %}{{ user.username }}{% endif %}<img class="down fr" src="{% static 'images/top_down.png' %}"/></dd>
                                    <dt><img width="20" height="20" src="{{ user.image.url }}"/></dt>
                                </dt>
                            </dl>
                            <div class="userdetail">
                                <dl>
                                        <dt><img width="80" height="80" src="{{ user.image.url }}"/></dt>
                                    </dt>
                                    <dd>
                                        <h2>{{ user.nick_name }}</h2>
                                            <p>{{ user.username }}</p>
                                    </dd>
                                </dl>
                                <div class="btn">
                                    <a class="personcenter fl" href="{% url 'users:info' %}">进入个人中心</a>
                                    <a class="fr" href="{% url 'logout' %}">退出</a>
                                </div>
                            </div>
                        </div>

                        </div>
                        </div>
                    {% else %}

                        <a style="color:white" class="fr registerbtn" href="register.html">注册</a>
                        <a style="color:white" class="fr loginbtn" href="{% url 'login' %}">登录</a>
                    {% endif %}


            <div class="middle">
                <div class="wp">
                    <a href="index.html"><img class="fl" src="./static/images/logo.jpg"/></a>
                    <div class="searchbox fr">
                        <div class="selectContainer fl">
                            <span class="selectOption" id="jsSelectOption" data-value="course">
                                公开课
                            </span>
                            <ul class="selectMenu" id="jsSelectMenu">
                                <li data-value="course">公开课</li>
                                <li data-value="org">课程机构</li>
                                <li data-value="teacher">授课老师</li>
                            </ul>
                        </div>
                        <input id="search_keywords" class="fl" type="text" value="" placeholder="请输入搜索内容"/>
                        <img class="search_btn fr" id="jsSearchBtn" src="./static/images/search_btn.png"/>
                    </div>
                </div>
            </div>


            <nav>
                <div class="nav">
                    <div class="wp">
                        <ul>
                            <li class="{% if request.path == '/' %}active{% endif %}"><a href="{% url 'index' %}">首页</a>
                            </li>
                            <li class="{% if request.path|slice:'7' == '/course' %}active{% endif %}">
                                <a href="{% url 'course:list' %}">
                                    公开课<img class="hot" src="/static/images/nav_hot.png">
                                </a>
                            </li>
                           <li class="{% if request.path|slice:'13' == '/org/teachers' %}active{% endif %}">
                                <a href="{% url 'org:teachers' %}">授课教师</a>
                            </li>
                             <li  class="{% if request.path|slice:'13' != '/org/teachers' %}active{% endif %}"><a href="{% url 'org:list' %}">授课机构</a></li>
                        </ul>
                    </div>
                </div>

                        </ul>
                    </div>
                </div>
            </nav>

        </div>
    </header>
</section>
<!--crumbs start-->

{% block custom_bread %}

{% endblock %}


{% block content %}

{% endblock %}
<footer>
    <div class="footer">
        <div class="wp">
            <ul class="cont">
                <li class="logo"><a href=""><img src="../images/footlogo.png"/></a></li>
                <li class="code"><img src="../images/code.jpg"/>
                    <p class="center">扫描关注微信</p></li>
                <li class="third"><img class="fl" src="../images/tell.png"/>
                    <p class="tell">400-888-888</p>
                    <p class="time">周一至周日 9:00-18:00</p></li>
            </ul>

        </div>
        <p class="line"></p>
        <div class="wp clear">
            <span class="fl">2020 www.muxuezaixian.com 慕学在线-在线学习交流平台 保留所有权利</span>
            <span class="fr">copyright ? 2020 ICP备案证书号：京ICP备xxxxx号-1</span>
        </div>
    </div>
</footer>

<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>
<script src="/static/js/selectUi.js" type='text/javascript'></script>
<script src="/static/js/deco-common.js" type='text/javascript'></script>
<script type="text/javascript" src="/static/js/plugins/laydate/laydate.js"></script>
<script src="/static/js/plugins/layer/layer.js"></script>
<script src="/static/js/plugins/queryCity/js/public.js" type="text/javascript"></script>
<script src="/static/js/unslider.js" type="text/javascript"></script>
<script src="/static/js/plugins/jquery.scrollLoading.js" type="text/javascript"></script>
<script src="/static/js/deco-common.js" type="text/javascript"></script>
{% block custom_js %}

{% endblock %}
</body>
</html>

templates/course-comment.html
{% extends 'base.html' %}
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul class="crumbs">

                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'course:list' %}">公开课</a>></li>
                {#        <li><a href="{% url 'course:detail' %}">课程详情</a>></li>#}
                <li>课程评论</li>

            </ul>
        </div>
    </section>
{% endblock %}
{% block custom_css %}
   <link rel="stylesheet" type="text/css" href="/static/css/muke/course/learn-less.css" />
	<link rel="stylesheet" type="text/css" href="/static/css/muke/course/course-comment.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/muke/base.css">
    <link rel="stylesheet" type="text/css" href="/static/css/muke/common-less.css">
    <link rel="stylesheet" type="text/css" href="/static/css/muke/course/common-less.css">
    <link rel="stylesheet" type="text/css" href="/static/css/mooc.css" />
{% endblock %}

{% block content %}

<div id="main">
<div class="course-infos">
    <div class="w pr">
        <div style="height: 15px" class="path">
        </div>
        <div class="hd">
            <h2 class="l">{{ course.name }}</h2>
        </div>
        <div class="statics clearfix">
            <div class="static-item ">
                <span class="meta-value"><strong>{{ course.get_degree_display }}</strong></span>
                <span class="meta">难度</span>
                <em></em>
            </div>
            <div class="static-item static-time">
                <span class="meta-value">{{ course.learn_times }}分钟</span>
                <span class="meta">时长</span>
                <em></em>
            </div>
            <div class="static-item">
                <span class="meta-value"><strong>{{ course.students }}</strong></span>
                <span class="meta">学习人数</span>
                <em></em>
            </div>
        </div>
    </div>
</div>
<div class="course-info-main clearfix w has-progress">

<div class="info-bar clearfix">
<div class="content-wrap clearfix">
    <div class="content">
        <div class="mod-tab-menu">
            <ul class="course-menu clearfix">
                <li><a class="ui-tabs-active " id="learnOn" href="{% url 'course:lesson' course.id %}"><span>章节</span></a>
                </li>
                <li><a id="commentOn" class="active" href="{% url 'course:comments' course.id %}"><span>评论</span></a></li>
            </ul>
        </div>

        <!--发布评论-->
        <div id="js-pub-container" class="issques clearfix js-form">
            <div class="wgt-ipt-wrap pub-editor-wrap " id="js-pl-input-fake">
                <textarea id="js-pl-textarea" class="" placeholder="扯淡、吐槽、表扬、鼓励……想说啥就说啥！"></textarea>
            </div>
            <input type="button" id="js-pl-submit" class="pub-btn" data-cid="452" value="发表评论">
            <p class="global-errortip js-global-error"></p>
        </div>
        <div id="course_note">
            <ul class="mod-post" id="comment-list">
                {% for comment in comments %}

                <li class="post-row">
                    <div class="media">
                        <span target="_blank"><img src='{{ comment.user.image.url }}'
                                                   width='40' height='40'/></span>
                    </div>
                    <div class="bd">
                        <div class="tit">
                            <span target="_blank">{% if comment.user.nick_name %}{{comment.user.nick_name}}{% else %}{{comment.user.username  }}{% endif %}</span>
                        </div>
                        <p class="cnt">
                            {{ comment.comments }}
                           </p>
                        <div class="footer clearfix">
                            <span title="创建时间" class="l timeago">时间：{{comment.add_time}}</span>
                        </div>
                    </div>
                </li>
                {% endfor %}



            </ul>
        </div>

    </div>
    <div class="aside r">
        <div class="bd">

            <div class="box mb40">
                <h4>资料下载</h4>
                <ul class="downlist">
                    {% for resource in course_resource %}
                        <li>
                            <span><i
                                    class="aui-iconfont aui-icon-file"></i>&nbsp;&nbsp;{{ resource.name }}</span>
                            <a href="{{ resource.file.url }}" class="downcode" target="_blank"
                               download="" data-id="274" title="">下载</a>
                        </li>
                    {% endfor %}


                </ul>
            </div>
            <div class="box mb40">
                <h4>讲师提示</h4>
                <div class="teacher-info">
                    <a href="#" target="_blank">
                        <img src='{{ course.teacher.image.url }}' width='80' height='80'/>
                    </a>
                    <span class="tit">
<a href="#" target="_blank">{{ course.teacher.name }}</a>
</span>
                    <span class="job">{{ course.teacher.work_position }}</span>
                </div>
                <div class="course-info-tip">
                    <dl class="first">
                        <dt>课程须知</dt>
                        <dd class="autowrap">{{ course.youneed_know }}</dd>
                    </dl>
                    <dl>
                        <dt>老师告诉你能学到什么？</dt>
                        <dd class="autowrap">{{ course.teacher_tell }}</dd>
                    </dl>
                </div>
            </div>


            <div class="cp-other-learned  js-comp-tabs">
                <div class="cp-header clearfix">
                    <h2 class="cp-tit l">该课的同学还学过</h2>
                </div>
                <div class="cp-body">
                    <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course"
                         style="display: block">
                        <!-- img 200 x 112 -->
                        <ul class="other-list">
                            {% for course in related_courses %}
                                <li class="curr">
                                    <a href="{% url 'course:detail' course.id %}" target="_blank">
                                        <img src="{{ course.image.url }}"
                                             alt="{{ course.name }}">
                                        <span class="name autowrap">{{ course.name }}</span>
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="plan">
                        <ul class="other-list">
                            <li class="curr">
                                <a href="/course/programdetail/pid/31?src=sug" target="_blank">
                                    <img src="http://img.mukewang.com/56551e6700018b0c09600720-240-135.jpg"
                                         alt="Java工程师">
                                    <span class="name autowrap">Java工程师</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
<div class="clear"></div>

</div>

</div>
</div>
{% endblock %}
{% block custom_js %}
    <script type="text/javascript">
        //添加评论
        $(document).ready(function () {
            $('#js-pl-submit').on('click', function () {
                var comments = $("#js-pl-textarea").val()
                if (comments == "") {
                    alert("评论不能为空")
                    return
                }
                $.ajax({
                    cache: false,
                    type: "POST",
                    url: "{% url 'op:comment'%}",
                    data: {'course': {{ course.id }}, 'comments': comments},
                    async: true,
                    beforeSend: function (xhr, settings) {
                        xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                    },
                    success: function (data) {
                        if (data.status == 'fail') {
                            if (data.msg == '用户未登录') {
                                window.location.href = "{% url 'login' %}";
                            } else {
                                alert(data.msg)
                            }

                        } else if (data.status == 'success') {
                            window.location.reload();//刷新当前页面.
                        }
                    },
                });
            });
        });

    </script>
{% endblock %}

templates/usercenter-mycourse.html
{% extends 'usercenter-base.html' %}
{% block title %}我的课程-慕学在线网{% endblock %}
{% block custom_bread %}
<section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'users:info' %}">个人中心</a>></li>
                <li>我的课程</li>
            </ul>
        </div>
    </section>
{% endblock %}
{% block right_form %}
<div class="right" >
		<div class="personal_des Releasecont">
			<div class="head">
				<h1>我的课程</h1>
			</div>
		</div>
		<div class="personal_des permessage">
			<div class="companycenter">
				<div class="group_list brief">
                    {% for user_course in user.usercourse_set.all %}
                    <div class="module1_5 box">
                            <a href="{% url 'course:detail' user_course.course.id %}">
                                <img width="214" height="190" class="scrollLoading" src="{{ user_course.course.image.url }}"/>
                            </a>
                            <div class="des">
                                <a href="course-detail.html"><h2>{{ user_course.course.name }}</h2></a>
                                <span class="fl">课时：<i class="key">{{ user_course.course.learn_times }}</i></span>
                                <span class="fr">学习人数：{{ user_course.course.students }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">北京大学</span>
                                <span class="star fr  notlogin" data-favid="15">0</span>
                            </div>
                        </div>
                    {% endfor %}
				</div>
			</div>
		</div>
	</div>
{% endblock %}